# ===============================
# = Spring configurations
# ===============================
spring:
  name: local
  # = HTTP requests configurations ##############################
  servlet:
    multipart:
      location: /tmp
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: Ashu1234
